name: qwen-codeforces
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - transformers>=4.35.0
  - datasets>=2.14.0
  - evaluate>=0.4.0
  - tqdm>=4.64.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - wandb>=0.15.0
  - accelerate>=0.24.0
  - sentencepiece>=0.1.99
  - protobuf>=3.20.0
  - tokenizers>=0.14.0
  - huggingface-hub>=0.17.0
  - pip
  - pip:
    - flash-attn  # Optional: for faster attention computation 